// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Repository;

#nullable disable

namespace Repository.Migrations.TestMigrations
{
    [DbContext(typeof(SQLiteContext))]
    partial class TestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Repository.Entities.Note", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("NotifierId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Read")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("RecipientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Repository.Entities.Penalty", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("PenalizedId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PenalizedId");

                    b.ToTable("Penalties");
                });

            modelBuilder.Entity("Repository.Entities.Subscription", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceType")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Repository.Gathering", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Athleticisme")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Chaos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Competitiveness")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Extroversion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupMaximum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupMinimum")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("HostId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Industriousness")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDynamic")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPendingDeletion")
                        .HasColumnType("INTEGER");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("POINT")
                        .HasAnnotation("Sqlite:Srid", 4326);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NightOwl")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Openness")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Radius")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Gatherings");
                });

            modelBuilder.Entity("Repository.GatheringLink", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GatheringId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GatheringId");

                    b.HasIndex("UserId");

                    b.ToTable("GatheringLinks");
                });

            modelBuilder.Entity("Repository.GatheringReport", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GatheringId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("FilingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GatheringId");

                    b.HasIndex("UserId");

                    b.ToTable("GatheringReports");
                });

            modelBuilder.Entity("Repository.Post", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GatheringId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotoURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("PostedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GatheringId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Repository.PostLink", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("PostId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId", "PostId")
                        .IsUnique();

                    b.ToTable("PostLinks");
                });

            modelBuilder.Entity("Repository.User", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessTries")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Athleticisme")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Chaos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Competitiveness")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("CurrentGathering")
                        .HasColumnType("INTEGER");

                    b.Property<Point>("CurrentLocation")
                        .IsRequired()
                        .HasColumnType("POINT")
                        .HasAnnotation("Sqlite:Srid", 4326);

                    b.Property<double>("CurrentRadius")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Extroversion")
                        .HasColumnType("INTEGER");

                    b.Property<Point>("Haunt")
                        .IsRequired()
                        .HasColumnType("POINT")
                        .HasAnnotation("Sqlite:Srid", 4326);

                    b.Property<double>("HauntRadius")
                        .HasColumnType("REAL");

                    b.Property<int>("HauntWheight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Industriousness")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPendingDeletion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPhoneConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("JoinDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LockoutDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NightOwl")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalisedEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Openness")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Reputation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Repository.UserLink", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("OtherId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("SelfId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OtherId");

                    b.HasIndex("SelfId");

                    b.ToTable("UserLinks");
                });

            modelBuilder.Entity("Repository.UserReport", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("GatheringId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("FilingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("OtherId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("SelfId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GatheringId");

                    b.HasIndex("OtherId");

                    b.HasIndex("SelfId");

                    b.ToTable("UserReports");
                });

            modelBuilder.Entity("Repository.Entities.Note", b =>
                {
                    b.HasOne("Repository.User", null)
                        .WithMany("Notes")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Repository.Entities.Penalty", b =>
                {
                    b.HasOne("Repository.User", "Penalized")
                        .WithMany("Penalties")
                        .HasForeignKey("PenalizedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Penalized");
                });

            modelBuilder.Entity("Repository.Entities.Subscription", b =>
                {
                    b.HasOne("Repository.User", null)
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Repository.GatheringLink", b =>
                {
                    b.HasOne("Repository.Gathering", "Gathering")
                        .WithMany("Links")
                        .HasForeignKey("GatheringId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.User", "User")
                        .WithMany("GatheringLinks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gathering");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.GatheringReport", b =>
                {
                    b.HasOne("Repository.Gathering", "Gathering")
                        .WithMany("Reports")
                        .HasForeignKey("GatheringId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.User", "Self")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gathering");

                    b.Navigation("Self");
                });

            modelBuilder.Entity("Repository.Post", b =>
                {
                    b.HasOne("Repository.Gathering", "Gathering")
                        .WithMany("Posts")
                        .HasForeignKey("GatheringId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.User", "Owner")
                        .WithMany("Posts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gathering");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Repository.PostLink", b =>
                {
                    b.HasOne("Repository.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.User", "User")
                        .WithMany("PostLinks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.UserLink", b =>
                {
                    b.HasOne("Repository.User", "Other")
                        .WithMany("UserLinks")
                        .HasForeignKey("OtherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.User", "Self")
                        .WithMany()
                        .HasForeignKey("SelfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Other");

                    b.Navigation("Self");
                });

            modelBuilder.Entity("Repository.UserReport", b =>
                {
                    b.HasOne("Repository.Gathering", "Gathering")
                        .WithMany()
                        .HasForeignKey("GatheringId");

                    b.HasOne("Repository.User", "Other")
                        .WithMany("ReporteeList")
                        .HasForeignKey("OtherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.User", "Self")
                        .WithMany("ReporterList")
                        .HasForeignKey("SelfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gathering");

                    b.Navigation("Other");

                    b.Navigation("Self");
                });

            modelBuilder.Entity("Repository.Gathering", b =>
                {
                    b.Navigation("Links");

                    b.Navigation("Posts");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("Repository.User", b =>
                {
                    b.Navigation("GatheringLinks");

                    b.Navigation("Notes");

                    b.Navigation("Penalties");

                    b.Navigation("PostLinks");

                    b.Navigation("Posts");

                    b.Navigation("ReporteeList");

                    b.Navigation("ReporterList");

                    b.Navigation("Subscriptions");

                    b.Navigation("UserLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
