// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Repository;

#nullable disable

namespace Repository.Migrations.TestMigrations
{
    [DbContext(typeof(TestContext))]
    partial class TestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Repository.Event", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Athleticisme")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Chaos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Competitiveness")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Extroversion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupMaximum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupMinimum")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("HostId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Industriousness")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDynamic")
                        .HasColumnType("INTEGER");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("POINT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NightOwl")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Openness")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Radius")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Repository.Link", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("OtherId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("OtherId");

                    b.Property<ulong>("SelfId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SelfId");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("TEXT");

                    b.Property<string>("link_type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Links");

                    b.HasDiscriminator<string>("link_type").HasValue("Link");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Repository.Post", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotoURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("PostedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Repository.Report", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("FilingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("OtherId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("SelfId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("report_type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("OtherId");

                    b.HasIndex("SelfId");

                    b.ToTable("Reports");

                    b.HasDiscriminator<string>("report_type").HasValue("Report");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Repository.User", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessTries")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AccountStatus");

                    b.Property<int>("Athleticisme")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Chaos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Competitiveness")
                        .HasColumnType("INTEGER");

                    b.Property<Point>("CurrentLocation")
                        .IsRequired()
                        .HasColumnType("POINT");

                    b.Property<double>("CurrentRadius")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Extroversion")
                        .HasColumnType("INTEGER");

                    b.Property<Point>("Haunt")
                        .IsRequired()
                        .HasColumnType("POINT");

                    b.Property<double>("HauntRadius")
                        .HasColumnType("REAL");

                    b.Property<int>("HauntWheight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Industriousness")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPhoneConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("JoinDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LockoutDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NightOwl")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalisedEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Openness")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Reputation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Repository.EventLink", b =>
                {
                    b.HasBaseType("Repository.Link");

                    b.Property<int>("Type")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Type");

                    b.HasDiscriminator().HasValue("event");
                });

            modelBuilder.Entity("Repository.PostLink", b =>
                {
                    b.HasBaseType("Repository.Link");

                    b.Property<int>("Type")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Type");

                    b.HasDiscriminator().HasValue("post");
                });

            modelBuilder.Entity("Repository.UserLink", b =>
                {
                    b.HasBaseType("Repository.Link");

                    b.Property<int>("Type")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Type");

                    b.HasDiscriminator().HasValue("user");
                });

            modelBuilder.Entity("Repository.EventReport", b =>
                {
                    b.HasBaseType("Repository.Report");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("event");
                });

            modelBuilder.Entity("Repository.UserReport", b =>
                {
                    b.HasBaseType("Repository.Report");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.ToTable("Reports", t =>
                        {
                            t.Property("Type")
                                .HasColumnName("UserReport_Type");
                        });

                    b.HasDiscriminator().HasValue("user");
                });

            modelBuilder.Entity("Repository.Report", b =>
                {
                    b.HasOne("Repository.Event", "Event")
                        .WithMany("Reports")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.User", "Other")
                        .WithMany("ReporteeList")
                        .HasForeignKey("OtherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.User", "Self")
                        .WithMany("ReporterList")
                        .HasForeignKey("SelfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Other");

                    b.Navigation("Self");
                });

            modelBuilder.Entity("Repository.Event", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("Repository.User", b =>
                {
                    b.Navigation("ReporteeList");

                    b.Navigation("ReporterList");
                });
#pragma warning restore 612, 618
        }
    }
}
