// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(QueryContext))]
    [Migration("20230202201539_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DataAccess.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("DataAccess.Entities.Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("SelfId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SelfId");

                    b.Property<string>("link_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SelfId");

                    b.ToTable("Links");

                    b.HasDiscriminator<string>("link_type").HasValue("Link");
                });

            modelBuilder.Entity("DataAccess.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessTries")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPhoneConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset?>("LockoutDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Reputation")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d047c5e7-8f32-474f-a466-66989c934b05"),
                            AccessTries = 0,
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "",
                            IsEmailConfirmed = false,
                            IsPhoneConfirmed = false,
                            JoinDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Signy of Sváfnir",
                            PhoneNumber = "0",
                            Reputation = 0,
                            SecurityStamp = "b77d02dd-352f-4539-885c-2ddff6b9b462"
                        },
                        new
                        {
                            Id = new Guid("5d4f8ae3-3414-445d-8a82-aeb632bfba91"),
                            AccessTries = 0,
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "",
                            IsEmailConfirmed = false,
                            IsPhoneConfirmed = false,
                            JoinDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Huginn",
                            PhoneNumber = "1",
                            Reputation = 0,
                            SecurityStamp = "01d89e9b-d1b1-460c-92c1-a61420692faf"
                        },
                        new
                        {
                            Id = new Guid("d9e5aed6-e9bc-4986-8f46-9c5aaf32f162"),
                            AccessTries = 0,
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "",
                            IsEmailConfirmed = false,
                            IsPhoneConfirmed = false,
                            JoinDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Muninn",
                            PhoneNumber = "2",
                            Reputation = 0,
                            SecurityStamp = "266a3179-8a1a-4324-8235-11f54f3bb42c"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.EventLink", b =>
                {
                    b.HasBaseType("DataAccess.Entities.Link");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("EventId");

                    b.HasDiscriminator().HasValue("event");
                });

            modelBuilder.Entity("DataAccess.Entities.UserLink", b =>
                {
                    b.HasBaseType("DataAccess.Entities.Link");

                    b.Property<Guid>("OtherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("Type");

                    b.HasDiscriminator().HasValue("user");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d2b05d8a-e3f2-43f6-a283-681deec2b607"),
                            SelfId = new Guid("5d4f8ae3-3414-445d-8a82-aeb632bfba91"),
                            OtherId = new Guid("d047c5e7-8f32-474f-a466-66989c934b05"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("07255625-ec32-45f3-b43d-7e0e06acf2e3"),
                            SelfId = new Guid("d9e5aed6-e9bc-4986-8f46-9c5aaf32f162"),
                            OtherId = new Guid("d047c5e7-8f32-474f-a466-66989c934b05"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("c84ed896-d491-4fde-ad20-46856a88d7aa"),
                            SelfId = new Guid("d047c5e7-8f32-474f-a466-66989c934b05"),
                            OtherId = new Guid("5d4f8ae3-3414-445d-8a82-aeb632bfba91"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("db9de99d-4c54-4a6e-a573-830ed264ff13"),
                            SelfId = new Guid("d047c5e7-8f32-474f-a466-66989c934b05"),
                            OtherId = new Guid("d9e5aed6-e9bc-4986-8f46-9c5aaf32f162"),
                            Type = 1
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Link", b =>
                {
                    b.HasOne("DataAccess.Entities.User", "Self")
                        .WithMany("Links")
                        .HasForeignKey("SelfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Self");
                });

            modelBuilder.Entity("DataAccess.Entities.EventLink", b =>
                {
                    b.HasOne("DataAccess.Entities.Event", "Event")
                        .WithMany("Links")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("DataAccess.Entities.Event", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("DataAccess.Entities.User", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
