// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(QueryContext))]
    [Migration("20230206041632_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DataAccess.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupMaximum")
                        .HasColumnType("int");

                    b.Property<int>("GroupMinimum")
                        .HasColumnType("int");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEventOpen")
                        .HasColumnType("bit");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8b004d57-ec57-4293-be01-3760a1be26c8"),
                            Description = "nothing interesting",
                            EndTime = new DateTimeOffset(new DateTime(800, 4, 3, 1, 37, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EventType = "campfire,stories",
                            GroupMaximum = 0,
                            GroupMinimum = 0,
                            HostId = new Guid("564bb3d4-c2cf-4278-9a0c-68da3eb782b3"),
                            IsEventOpen = false,
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4237;POINT (0 0)"),
                            Name = "The First Few",
                            StartTime = new DateTimeOffset(new DateTime(800, 4, 2, 18, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("89d9f649-cb8e-4f97-9014-da3576c4d0d8"),
                            Description = "still nothing interesting",
                            EndTime = new DateTimeOffset(new DateTime(800, 11, 4, 11, 3, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EventType = "skiing,drinks,rager",
                            GroupMaximum = 0,
                            GroupMinimum = 0,
                            HostId = new Guid("564bb3d4-c2cf-4278-9a0c-68da3eb782b3"),
                            IsEventOpen = false,
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4237;POINT (0 0)"),
                            Name = "Then There Were Two",
                            StartTime = new DateTimeOffset(new DateTime(800, 11, 2, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("2f07003e-a3ca-4688-b1e8-1e4373afe615"),
                            Description = "something interesting",
                            EventType = "chill,drinks",
                            GroupMaximum = 0,
                            GroupMinimum = 0,
                            HostId = new Guid("73acf8c3-a2fd-41d3-af27-43215fd0637f"),
                            IsEventOpen = false,
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4237;POINT (23.4413325 -76.0092066)"),
                            Name = "Masquerade",
                            StartTime = new DateTimeOffset(new DateTime(2025, 6, 25, 17, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("SelfId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SelfId");

                    b.Property<string>("link_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SelfId");

                    b.ToTable("Links");

                    b.HasDiscriminator<string>("link_type").HasValue("Link");
                });

            modelBuilder.Entity("DataAccess.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessTries")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DateOfBirth")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPhoneConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("JoinDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LockoutDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Reputation")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("73acf8c3-a2fd-41d3-af27-43215fd0637f"),
                            AccessTries = 0,
                            DateOfBirth = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "",
                            IsEmailConfirmed = false,
                            IsPhoneConfirmed = false,
                            JoinDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Signy of Sváfnir",
                            PhoneNumber = "0",
                            Reputation = 0,
                            SecurityStamp = "99669718-9f64-4a64-9067-45cfc0ee19ef"
                        },
                        new
                        {
                            Id = new Guid("564bb3d4-c2cf-4278-9a0c-68da3eb782b3"),
                            AccessTries = 0,
                            DateOfBirth = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "",
                            IsEmailConfirmed = false,
                            IsPhoneConfirmed = false,
                            JoinDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Huginn",
                            PhoneNumber = "1",
                            Reputation = 0,
                            SecurityStamp = "604a41c9-1d3f-4e31-8576-184807b7835a"
                        },
                        new
                        {
                            Id = new Guid("ecb85ed0-1628-4ae2-81bb-0e9bb3bdb6b8"),
                            AccessTries = 0,
                            DateOfBirth = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "",
                            IsEmailConfirmed = false,
                            IsPhoneConfirmed = false,
                            JoinDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Muninn",
                            PhoneNumber = "2",
                            Reputation = 0,
                            SecurityStamp = "f3442a23-3b33-4cf7-95d2-e0bd3ac379cb"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.EventLink", b =>
                {
                    b.HasBaseType("DataAccess.Entities.Link");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("EventId");

                    b.HasDiscriminator().HasValue("event");

                    b.HasData(
                        new
                        {
                            Id = new Guid("748b5d38-286e-4917-83a7-50d73f63058a"),
                            SelfId = new Guid("73acf8c3-a2fd-41d3-af27-43215fd0637f"),
                            EventId = new Guid("8b004d57-ec57-4293-be01-3760a1be26c8")
                        },
                        new
                        {
                            Id = new Guid("c931bfbb-136f-4bf6-b8ea-a37c913c12ca"),
                            SelfId = new Guid("564bb3d4-c2cf-4278-9a0c-68da3eb782b3"),
                            EventId = new Guid("8b004d57-ec57-4293-be01-3760a1be26c8")
                        },
                        new
                        {
                            Id = new Guid("13b3ccb5-bd9e-422d-9cfe-72c82a973c9c"),
                            SelfId = new Guid("ecb85ed0-1628-4ae2-81bb-0e9bb3bdb6b8"),
                            EventId = new Guid("8b004d57-ec57-4293-be01-3760a1be26c8")
                        },
                        new
                        {
                            Id = new Guid("e20dbc09-aa27-4cf4-84a3-abb5a8d941dd"),
                            SelfId = new Guid("73acf8c3-a2fd-41d3-af27-43215fd0637f"),
                            EventId = new Guid("89d9f649-cb8e-4f97-9014-da3576c4d0d8")
                        },
                        new
                        {
                            Id = new Guid("f2180438-d129-4877-af66-07626068ef8b"),
                            SelfId = new Guid("564bb3d4-c2cf-4278-9a0c-68da3eb782b3"),
                            EventId = new Guid("89d9f649-cb8e-4f97-9014-da3576c4d0d8")
                        },
                        new
                        {
                            Id = new Guid("99861b00-fdd1-4f4b-881a-b00fa227a5a8"),
                            SelfId = new Guid("73acf8c3-a2fd-41d3-af27-43215fd0637f"),
                            EventId = new Guid("2f07003e-a3ca-4688-b1e8-1e4373afe615")
                        },
                        new
                        {
                            Id = new Guid("c44be1cb-b8ce-4349-a9f2-dc16d13c6063"),
                            SelfId = new Guid("564bb3d4-c2cf-4278-9a0c-68da3eb782b3"),
                            EventId = new Guid("2f07003e-a3ca-4688-b1e8-1e4373afe615")
                        },
                        new
                        {
                            Id = new Guid("3f5c5b71-b28a-4379-b1a7-6ac808e4d190"),
                            SelfId = new Guid("ecb85ed0-1628-4ae2-81bb-0e9bb3bdb6b8"),
                            EventId = new Guid("2f07003e-a3ca-4688-b1e8-1e4373afe615")
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.UserLink", b =>
                {
                    b.HasBaseType("DataAccess.Entities.Link");

                    b.Property<Guid>("OtherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("Type");

                    b.HasDiscriminator().HasValue("user");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f4841190-57aa-440a-8d4f-a8f124629fbd"),
                            SelfId = new Guid("564bb3d4-c2cf-4278-9a0c-68da3eb782b3"),
                            OtherId = new Guid("73acf8c3-a2fd-41d3-af27-43215fd0637f"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("2d99ec49-5ff1-40bf-ac22-8115cbb6d76e"),
                            SelfId = new Guid("ecb85ed0-1628-4ae2-81bb-0e9bb3bdb6b8"),
                            OtherId = new Guid("73acf8c3-a2fd-41d3-af27-43215fd0637f"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("e7a57830-7600-42ad-a138-728f638d84dd"),
                            SelfId = new Guid("73acf8c3-a2fd-41d3-af27-43215fd0637f"),
                            OtherId = new Guid("564bb3d4-c2cf-4278-9a0c-68da3eb782b3"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("135661a5-7b71-44cc-ad0b-f83e16a3c36a"),
                            SelfId = new Guid("73acf8c3-a2fd-41d3-af27-43215fd0637f"),
                            OtherId = new Guid("ecb85ed0-1628-4ae2-81bb-0e9bb3bdb6b8"),
                            Type = 1
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Link", b =>
                {
                    b.HasOne("DataAccess.Entities.User", "Self")
                        .WithMany("Links")
                        .HasForeignKey("SelfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Self");
                });

            modelBuilder.Entity("DataAccess.Entities.EventLink", b =>
                {
                    b.HasOne("DataAccess.Entities.Event", "Event")
                        .WithMany("Links")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("DataAccess.Entities.Event", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("DataAccess.Entities.User", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
