// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(QueryContext))]
    partial class QueryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DataAccess.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupMaximum")
                        .HasColumnType("int");

                    b.Property<int>("GroupMinimum")
                        .HasColumnType("int");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEventOpen")
                        .HasColumnType("bit");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b98dc4a7-66fd-41be-9ac1-70ef12875472"),
                            Description = "nothing interesting",
                            EndTime = new DateTimeOffset(new DateTime(800, 4, 3, 1, 37, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EventType = "campfire,stories",
                            GroupMaximum = 0,
                            GroupMinimum = 0,
                            HostId = new Guid("5df33e44-2e1a-4cb7-8296-bd098f6e32b9"),
                            IsEventOpen = false,
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4237;POINT (0 0)"),
                            Name = "The First Few",
                            StartTime = new DateTimeOffset(new DateTime(800, 4, 2, 18, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("43a9001a-c220-42c0-8db2-78e448340ef7"),
                            Description = "still nothing interesting",
                            EndTime = new DateTimeOffset(new DateTime(800, 11, 4, 11, 3, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EventType = "skiing,drinks,rager",
                            GroupMaximum = 0,
                            GroupMinimum = 0,
                            HostId = new Guid("5df33e44-2e1a-4cb7-8296-bd098f6e32b9"),
                            IsEventOpen = false,
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4237;POINT (0 0)"),
                            Name = "Then There Were Two",
                            StartTime = new DateTimeOffset(new DateTime(800, 11, 2, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("72b1c2e9-88ca-477a-869e-71eeb555d813"),
                            Description = "something interesting",
                            EventType = "chill,drinks",
                            GroupMaximum = 0,
                            GroupMinimum = 0,
                            HostId = new Guid("53c8a2cf-46dd-435c-a5dd-6130c2c3d408"),
                            IsEventOpen = false,
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4237;POINT (23.4413325 -76.0092066)"),
                            Name = "Masquerade",
                            StartTime = new DateTimeOffset(new DateTime(2025, 6, 25, 17, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SelfId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SelfId");

                    b.Property<string>("link_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SelfId");

                    b.ToTable("Links");

                    b.HasDiscriminator<string>("link_type").HasValue("Link");
                });

            modelBuilder.Entity("DataAccess.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessTries")
                        .HasColumnType("int");

                    b.Property<int>("AccountStatus")
                        .HasColumnType("int")
                        .HasColumnName("AccountStatus");

                    b.Property<DateTimeOffset>("DateOfBirth")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPhoneConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("JoinDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LockoutDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalisedEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Reputation")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("53c8a2cf-46dd-435c-a5dd-6130c2c3d408"),
                            AccessTries = 0,
                            AccountStatus = 0,
                            DateOfBirth = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "",
                            IsEmailConfirmed = false,
                            IsPhoneConfirmed = false,
                            JoinDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Signy of Sváfnir",
                            NormalisedEmail = "",
                            PhoneNumber = "0",
                            Reputation = 0,
                            SecurityStamp = "b6462001-08c7-43ef-bff8-824ef5819d95"
                        },
                        new
                        {
                            Id = new Guid("5df33e44-2e1a-4cb7-8296-bd098f6e32b9"),
                            AccessTries = 0,
                            AccountStatus = 0,
                            DateOfBirth = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "",
                            IsEmailConfirmed = false,
                            IsPhoneConfirmed = false,
                            JoinDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Huginn",
                            NormalisedEmail = "",
                            PhoneNumber = "1",
                            Reputation = 0,
                            SecurityStamp = "675a78f2-5038-4c51-b9a9-f639e194d2de"
                        },
                        new
                        {
                            Id = new Guid("b4940b9e-bb9b-49dc-a9ee-458a3feb76f5"),
                            AccessTries = 0,
                            AccountStatus = 0,
                            DateOfBirth = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "",
                            IsEmailConfirmed = false,
                            IsPhoneConfirmed = false,
                            JoinDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Muninn",
                            NormalisedEmail = "",
                            PhoneNumber = "2",
                            Reputation = 0,
                            SecurityStamp = "dc97fd04-ec68-41d0-80ad-20df7c858ea9"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.EventLink", b =>
                {
                    b.HasBaseType("DataAccess.Entities.Link");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("Type");

                    b.HasIndex("EventId");

                    b.HasDiscriminator().HasValue("event");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9989ae13-874e-42ca-b73a-493e9f624f21"),
                            SelfId = new Guid("53c8a2cf-46dd-435c-a5dd-6130c2c3d408"),
                            EventId = new Guid("b98dc4a7-66fd-41be-9ac1-70ef12875472"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a9d20a93-b0b1-4cca-9b73-9cca7c5c10a3"),
                            SelfId = new Guid("5df33e44-2e1a-4cb7-8296-bd098f6e32b9"),
                            EventId = new Guid("b98dc4a7-66fd-41be-9ac1-70ef12875472"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("7ac4cb6f-1d4a-4bea-aa4f-8e129bead1b5"),
                            SelfId = new Guid("b4940b9e-bb9b-49dc-a9ee-458a3feb76f5"),
                            EventId = new Guid("b98dc4a7-66fd-41be-9ac1-70ef12875472"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("bf256884-4360-4d3a-a669-7f964eaeadfb"),
                            SelfId = new Guid("53c8a2cf-46dd-435c-a5dd-6130c2c3d408"),
                            EventId = new Guid("43a9001a-c220-42c0-8db2-78e448340ef7"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("34621ad4-75cc-49bb-a046-4d93a8d42492"),
                            SelfId = new Guid("5df33e44-2e1a-4cb7-8296-bd098f6e32b9"),
                            EventId = new Guid("43a9001a-c220-42c0-8db2-78e448340ef7"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("e96c1719-6121-4877-9793-20ec046d8d28"),
                            SelfId = new Guid("53c8a2cf-46dd-435c-a5dd-6130c2c3d408"),
                            EventId = new Guid("72b1c2e9-88ca-477a-869e-71eeb555d813"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("c16f67ad-e638-40a7-9e60-3851276dddfd"),
                            SelfId = new Guid("5df33e44-2e1a-4cb7-8296-bd098f6e32b9"),
                            EventId = new Guid("72b1c2e9-88ca-477a-869e-71eeb555d813"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("699ba422-0ad7-4439-96ff-db6f67d44ce1"),
                            SelfId = new Guid("b4940b9e-bb9b-49dc-a9ee-458a3feb76f5"),
                            EventId = new Guid("72b1c2e9-88ca-477a-869e-71eeb555d813"),
                            Type = 1
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.UserLink", b =>
                {
                    b.HasBaseType("DataAccess.Entities.Link");

                    b.Property<Guid>("OtherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("Type");

                    b.HasDiscriminator().HasValue("user");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b3c3f836-7640-4f59-803c-0ebaf212ba90"),
                            SelfId = new Guid("5df33e44-2e1a-4cb7-8296-bd098f6e32b9"),
                            OtherId = new Guid("53c8a2cf-46dd-435c-a5dd-6130c2c3d408"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("8942bda0-aab2-4219-8e4f-dd0c5d3f8374"),
                            SelfId = new Guid("b4940b9e-bb9b-49dc-a9ee-458a3feb76f5"),
                            OtherId = new Guid("53c8a2cf-46dd-435c-a5dd-6130c2c3d408"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("96e2a779-fd82-4018-9565-a3c2612be074"),
                            SelfId = new Guid("53c8a2cf-46dd-435c-a5dd-6130c2c3d408"),
                            OtherId = new Guid("5df33e44-2e1a-4cb7-8296-bd098f6e32b9"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a24b5b3e-0c7a-4d66-a839-ba66cdb0cbdf"),
                            SelfId = new Guid("53c8a2cf-46dd-435c-a5dd-6130c2c3d408"),
                            OtherId = new Guid("b4940b9e-bb9b-49dc-a9ee-458a3feb76f5"),
                            Type = 1
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Link", b =>
                {
                    b.HasOne("DataAccess.Entities.User", "Self")
                        .WithMany("Links")
                        .HasForeignKey("SelfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Self");
                });

            modelBuilder.Entity("DataAccess.Entities.EventLink", b =>
                {
                    b.HasOne("DataAccess.Entities.Event", "Event")
                        .WithMany("Links")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("DataAccess.Entities.Event", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("DataAccess.Entities.User", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
