// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(QueryContext))]
    partial class QueryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DataAccess.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("GroupMaximum")
                        .HasColumnType("int");

                    b.Property<int>("GroupMinimum")
                        .HasColumnType("int");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEventOpen")
                        .HasColumnType("bit");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d99961f5-1332-4bf3-80a0-2fd9d27e5d4e"),
                            Description = "nothing interesting",
                            EndTime = new DateTimeOffset(new DateTime(800, 4, 3, 1, 37, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            GroupMaximum = 0,
                            GroupMinimum = 0,
                            HostId = new Guid("3dcf1d47-7322-439a-8011-9091a0ba8b99"),
                            IsEventOpen = false,
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4237;POINT (0 0)"),
                            Name = "The First Few",
                            StartTime = new DateTimeOffset(new DateTime(800, 4, 2, 18, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Type = "campfire,stories"
                        },
                        new
                        {
                            Id = new Guid("a658d8a4-8dbe-4cc5-99cc-1d9a7c1ace77"),
                            Description = "still nothing interesting",
                            EndTime = new DateTimeOffset(new DateTime(800, 11, 4, 11, 3, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            GroupMaximum = 0,
                            GroupMinimum = 0,
                            HostId = new Guid("3dcf1d47-7322-439a-8011-9091a0ba8b99"),
                            IsEventOpen = false,
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4237;POINT (0 0)"),
                            Name = "Then There Were Two",
                            StartTime = new DateTimeOffset(new DateTime(800, 11, 2, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Type = "skiing,drinks,rager"
                        },
                        new
                        {
                            Id = new Guid("ca8e2ea7-204f-4ac5-bb1e-6b7c1752ec8e"),
                            Description = "something interesting",
                            GroupMaximum = 0,
                            GroupMinimum = 0,
                            HostId = new Guid("d365de18-b3cf-4945-92ba-0bd4db2b4b18"),
                            IsEventOpen = false,
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4237;POINT (23.4413325 -76.0092066)"),
                            Name = "Masquerade",
                            StartTime = new DateTimeOffset(new DateTime(2025, 6, 25, 17, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Type = "chill,drinks"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SelfId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SelfId");

                    b.Property<string>("link_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SelfId");

                    b.ToTable("Links");

                    b.HasDiscriminator<string>("link_type").HasValue("Link");
                });

            modelBuilder.Entity("DataAccess.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessTries")
                        .HasColumnType("int");

                    b.Property<int>("AccountStatus")
                        .HasColumnType("int")
                        .HasColumnName("AccountStatus");

                    b.Property<DateTimeOffset>("DateOfBirth")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPhoneConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("JoinDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LockoutDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalisedEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Reputation")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d365de18-b3cf-4945-92ba-0bd4db2b4b18"),
                            AccessTries = 0,
                            AccountStatus = 0,
                            DateOfBirth = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "",
                            IsEmailConfirmed = false,
                            IsPhoneConfirmed = false,
                            JoinDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Signy of Sváfnir",
                            NormalisedEmail = "",
                            PhoneNumber = "0",
                            Reputation = 0,
                            SecurityStamp = "266a9a20-36ab-49cc-aa1d-ee0526858bbb"
                        },
                        new
                        {
                            Id = new Guid("3dcf1d47-7322-439a-8011-9091a0ba8b99"),
                            AccessTries = 0,
                            AccountStatus = 0,
                            DateOfBirth = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "",
                            IsEmailConfirmed = false,
                            IsPhoneConfirmed = false,
                            JoinDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Huginn",
                            NormalisedEmail = "",
                            PhoneNumber = "1",
                            Reputation = 0,
                            SecurityStamp = "8123c3e1-85ab-48d2-b2df-be704b35f133"
                        },
                        new
                        {
                            Id = new Guid("c75de3b0-f166-4894-bee5-98cff6ade6ce"),
                            AccessTries = 0,
                            AccountStatus = 0,
                            DateOfBirth = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "",
                            IsEmailConfirmed = false,
                            IsPhoneConfirmed = false,
                            JoinDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Muninn",
                            NormalisedEmail = "",
                            PhoneNumber = "2",
                            Reputation = 0,
                            SecurityStamp = "6718008d-be8a-4a73-a3dd-0518ec7a3d77"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.EventLink", b =>
                {
                    b.HasBaseType("DataAccess.Entities.Link");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("Type");

                    b.HasIndex("EventId");

                    b.HasDiscriminator().HasValue("event");

                    b.HasData(
                        new
                        {
                            Id = new Guid("67586de8-db04-4802-814b-78c665ed8cbd"),
                            SelfId = new Guid("d365de18-b3cf-4945-92ba-0bd4db2b4b18"),
                            EventId = new Guid("d99961f5-1332-4bf3-80a0-2fd9d27e5d4e"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("fa59fbea-17c3-412e-9a63-d837020aa19f"),
                            SelfId = new Guid("3dcf1d47-7322-439a-8011-9091a0ba8b99"),
                            EventId = new Guid("d99961f5-1332-4bf3-80a0-2fd9d27e5d4e"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("d404b40a-5405-4b3c-ace2-cd086efbbb07"),
                            SelfId = new Guid("c75de3b0-f166-4894-bee5-98cff6ade6ce"),
                            EventId = new Guid("d99961f5-1332-4bf3-80a0-2fd9d27e5d4e"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("d3c8b3cc-93b2-4916-8ea4-32355687ecda"),
                            SelfId = new Guid("d365de18-b3cf-4945-92ba-0bd4db2b4b18"),
                            EventId = new Guid("a658d8a4-8dbe-4cc5-99cc-1d9a7c1ace77"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("fc018845-eab2-43b1-8de5-c85559b9082e"),
                            SelfId = new Guid("3dcf1d47-7322-439a-8011-9091a0ba8b99"),
                            EventId = new Guid("a658d8a4-8dbe-4cc5-99cc-1d9a7c1ace77"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("6e64b50d-596e-49d9-95cb-97b73b86f766"),
                            SelfId = new Guid("d365de18-b3cf-4945-92ba-0bd4db2b4b18"),
                            EventId = new Guid("ca8e2ea7-204f-4ac5-bb1e-6b7c1752ec8e"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("495f866c-3f1f-4f6a-b058-86fb214977d2"),
                            SelfId = new Guid("3dcf1d47-7322-439a-8011-9091a0ba8b99"),
                            EventId = new Guid("ca8e2ea7-204f-4ac5-bb1e-6b7c1752ec8e"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("1c5be907-e057-4c08-9ca0-a8e646a4fe01"),
                            SelfId = new Guid("c75de3b0-f166-4894-bee5-98cff6ade6ce"),
                            EventId = new Guid("ca8e2ea7-204f-4ac5-bb1e-6b7c1752ec8e"),
                            Type = 1
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.UserLink", b =>
                {
                    b.HasBaseType("DataAccess.Entities.Link");

                    b.Property<Guid>("OtherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("Type");

                    b.HasDiscriminator().HasValue("user");

                    b.HasData(
                        new
                        {
                            Id = new Guid("02cac8f7-bb56-4807-a510-e1e6a0de3fb0"),
                            SelfId = new Guid("3dcf1d47-7322-439a-8011-9091a0ba8b99"),
                            OtherId = new Guid("d365de18-b3cf-4945-92ba-0bd4db2b4b18"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("6b5b70aa-ade5-4266-b8de-a71a8d119d68"),
                            SelfId = new Guid("c75de3b0-f166-4894-bee5-98cff6ade6ce"),
                            OtherId = new Guid("d365de18-b3cf-4945-92ba-0bd4db2b4b18"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("22400f6e-c402-4fdf-998b-b536207b4d4d"),
                            SelfId = new Guid("d365de18-b3cf-4945-92ba-0bd4db2b4b18"),
                            OtherId = new Guid("3dcf1d47-7322-439a-8011-9091a0ba8b99"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("af62a095-506a-4ec5-8e90-cb33beea92b6"),
                            SelfId = new Guid("d365de18-b3cf-4945-92ba-0bd4db2b4b18"),
                            OtherId = new Guid("c75de3b0-f166-4894-bee5-98cff6ade6ce"),
                            Type = 1
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Link", b =>
                {
                    b.HasOne("DataAccess.Entities.User", "Self")
                        .WithMany("Links")
                        .HasForeignKey("SelfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Self");
                });

            modelBuilder.Entity("DataAccess.Entities.EventLink", b =>
                {
                    b.HasOne("DataAccess.Entities.Event", "Event")
                        .WithMany("Links")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("DataAccess.Entities.Event", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("DataAccess.Entities.User", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
