// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(QueryContext))]
    partial class QueryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DataAccess.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupMaximum")
                        .HasColumnType("int");

                    b.Property<int>("GroupMinimum")
                        .HasColumnType("int");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEventOpen")
                        .HasColumnType("bit");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22ea9e48-6528-4e8e-94b5-6a340431a140"),
                            Description = "nothing interesting",
                            EndTime = new DateTimeOffset(new DateTime(800, 4, 3, 1, 37, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EventType = "campfire,stories",
                            GroupMaximum = 0,
                            GroupMinimum = 0,
                            HostId = new Guid("2fe22508-b1c7-4243-9070-926172684da2"),
                            IsEventOpen = false,
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4237;POINT (0 0)"),
                            Name = "The First Few",
                            StartTime = new DateTimeOffset(new DateTime(800, 4, 2, 18, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("903aea86-698d-4f18-ba24-be6ee3d16566"),
                            Description = "still nothing interesting",
                            EndTime = new DateTimeOffset(new DateTime(800, 11, 4, 11, 3, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EventType = "skiing,drinks,rager",
                            GroupMaximum = 0,
                            GroupMinimum = 0,
                            HostId = new Guid("2fe22508-b1c7-4243-9070-926172684da2"),
                            IsEventOpen = false,
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4237;POINT (0 0)"),
                            Name = "Then There Were Two",
                            StartTime = new DateTimeOffset(new DateTime(800, 11, 2, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("540ec6e6-5342-4350-92ec-a94e684b5df3"),
                            Description = "something interesting",
                            EventType = "chill,drinks",
                            GroupMaximum = 0,
                            GroupMinimum = 0,
                            HostId = new Guid("8b043af7-c35b-463e-a2eb-b9cb36d38426"),
                            IsEventOpen = false,
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4237;POINT (23.4413325 -76.0092066)"),
                            Name = "Masquerade",
                            StartTime = new DateTimeOffset(new DateTime(2025, 6, 25, 17, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SelfId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SelfId");

                    b.Property<string>("link_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SelfId");

                    b.ToTable("Links");

                    b.HasDiscriminator<string>("link_type").HasValue("Link");
                });

            modelBuilder.Entity("DataAccess.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessTries")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DateOfBirth")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPhoneConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("JoinDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LockoutDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalisedEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Reputation")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8b043af7-c35b-463e-a2eb-b9cb36d38426"),
                            AccessTries = 0,
                            DateOfBirth = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "",
                            IsEmailConfirmed = false,
                            IsPhoneConfirmed = false,
                            JoinDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Signy of Sváfnir",
                            NormalisedEmail = "",
                            PhoneNumber = "0",
                            Reputation = 0,
                            SecurityStamp = "25370e4b-384f-41be-80f6-97e4abcdff52"
                        },
                        new
                        {
                            Id = new Guid("2fe22508-b1c7-4243-9070-926172684da2"),
                            AccessTries = 0,
                            DateOfBirth = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "",
                            IsEmailConfirmed = false,
                            IsPhoneConfirmed = false,
                            JoinDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Huginn",
                            NormalisedEmail = "",
                            PhoneNumber = "1",
                            Reputation = 0,
                            SecurityStamp = "260e2456-8712-4c3f-b68c-7b5d483961e6"
                        },
                        new
                        {
                            Id = new Guid("d6430eeb-a7cc-4ef9-a851-6cde9376b9bf"),
                            AccessTries = 0,
                            DateOfBirth = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "",
                            IsEmailConfirmed = false,
                            IsPhoneConfirmed = false,
                            JoinDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Muninn",
                            NormalisedEmail = "",
                            PhoneNumber = "2",
                            Reputation = 0,
                            SecurityStamp = "16c5a432-2da9-4380-82f4-4f30131fd200"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.EventLink", b =>
                {
                    b.HasBaseType("DataAccess.Entities.Link");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("Type");

                    b.HasIndex("EventId");

                    b.HasDiscriminator().HasValue("event");

                    b.HasData(
                        new
                        {
                            Id = new Guid("03b1d5fa-6d91-4fbd-b88d-5e4700030f0c"),
                            SelfId = new Guid("8b043af7-c35b-463e-a2eb-b9cb36d38426"),
                            EventId = new Guid("22ea9e48-6528-4e8e-94b5-6a340431a140"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("56c3dad2-8a5b-4c2c-9472-86427844dad9"),
                            SelfId = new Guid("2fe22508-b1c7-4243-9070-926172684da2"),
                            EventId = new Guid("22ea9e48-6528-4e8e-94b5-6a340431a140"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("19c141ab-3f37-427c-ba5b-e8fbc87e9cd2"),
                            SelfId = new Guid("d6430eeb-a7cc-4ef9-a851-6cde9376b9bf"),
                            EventId = new Guid("22ea9e48-6528-4e8e-94b5-6a340431a140"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("6ba2518b-0352-4769-a453-5cec43bdaeb9"),
                            SelfId = new Guid("8b043af7-c35b-463e-a2eb-b9cb36d38426"),
                            EventId = new Guid("903aea86-698d-4f18-ba24-be6ee3d16566"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("b2862eb0-1407-4b2e-8410-d6f3854134b2"),
                            SelfId = new Guid("2fe22508-b1c7-4243-9070-926172684da2"),
                            EventId = new Guid("903aea86-698d-4f18-ba24-be6ee3d16566"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("7fbf2eb9-3e9e-4782-b1d8-101b315c9d19"),
                            SelfId = new Guid("8b043af7-c35b-463e-a2eb-b9cb36d38426"),
                            EventId = new Guid("540ec6e6-5342-4350-92ec-a94e684b5df3"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("6bb343da-74dc-4584-9ff9-e732cc457854"),
                            SelfId = new Guid("2fe22508-b1c7-4243-9070-926172684da2"),
                            EventId = new Guid("540ec6e6-5342-4350-92ec-a94e684b5df3"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("bdd00760-019b-42ca-b27b-4325fc001560"),
                            SelfId = new Guid("d6430eeb-a7cc-4ef9-a851-6cde9376b9bf"),
                            EventId = new Guid("540ec6e6-5342-4350-92ec-a94e684b5df3"),
                            Type = 1
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.UserLink", b =>
                {
                    b.HasBaseType("DataAccess.Entities.Link");

                    b.Property<Guid>("OtherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("Type");

                    b.HasDiscriminator().HasValue("user");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5d1ed340-a6e7-41c3-9d61-1da12bb60ad2"),
                            SelfId = new Guid("2fe22508-b1c7-4243-9070-926172684da2"),
                            OtherId = new Guid("8b043af7-c35b-463e-a2eb-b9cb36d38426"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("298a9a8d-b2f2-4df6-a043-26a8c7f848d2"),
                            SelfId = new Guid("d6430eeb-a7cc-4ef9-a851-6cde9376b9bf"),
                            OtherId = new Guid("8b043af7-c35b-463e-a2eb-b9cb36d38426"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("26863755-e02b-4d84-8678-89b3b86d2310"),
                            SelfId = new Guid("8b043af7-c35b-463e-a2eb-b9cb36d38426"),
                            OtherId = new Guid("2fe22508-b1c7-4243-9070-926172684da2"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("bad9512b-5f0a-4165-88bf-893c2ddc3118"),
                            SelfId = new Guid("8b043af7-c35b-463e-a2eb-b9cb36d38426"),
                            OtherId = new Guid("d6430eeb-a7cc-4ef9-a851-6cde9376b9bf"),
                            Type = 1
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Link", b =>
                {
                    b.HasOne("DataAccess.Entities.User", "Self")
                        .WithMany("Links")
                        .HasForeignKey("SelfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Self");
                });

            modelBuilder.Entity("DataAccess.Entities.EventLink", b =>
                {
                    b.HasOne("DataAccess.Entities.Event", "Event")
                        .WithMany("Links")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("DataAccess.Entities.Event", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("DataAccess.Entities.User", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
